server:
  port: 8081
  servlet:
    context-path: /*
    session:
      cookie:
        http-only: true
        tracking-modes: cookie
#  ssl:
#    key-alias: https_space_marine_base
#    key-password: 121234
#    key-store-type: JKS
#    key-store: classpath:https_space_marine_base.jks

postgresql:
  host: 127.0.0.1
  port: 5432
  database: postgres
  username: postgres
  password: postgres

spring:
  application:
    name: space_marine
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://${postgresql.host}:${postgresql.port}/${postgresql.database}
    username: ${postgresql.username}
    password: ${postgresql.password}
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
    platform: postgres
    initialization-mode: always
